# Generated by Django 2.1.7 on 2019-04-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language_name',
            field=models.CharField(choices=[('E', 'English'), ('G', 'Georgian'), ('R', 'Russian')], help_text='Enter a book language (e.g Science Fiction', max_length=200),
        ),
    ]
