# Generated by Django 2.1.7 on 2019-04-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20190414_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language_name',
            field=models.CharField(choices=[('Eng', 'English'), ('Geo', 'Georgian'), ('Rus', 'Russian')], help_text='Available language', max_length=20),
        ),
    ]
