# Generated by Django 2.1.7 on 2019-04-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20190414_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='id',
        ),
        migrations.AlterField(
            model_name='language',
            name='language_name',
            field=models.CharField(choices=[('English', 'English'), ('Georgina', 'Georgian'), ('Russian', 'Russian')], help_text='Book language availability', max_length=20, primary_key=True, serialize=False),
        ),
    ]
