# Generated by Django 2.1.7 on 2019-04-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20190415_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language_name',
            field=models.AutoField(choices=[('English', 'English'), ('Georgina', 'Georgian'), ('Russian', 'Russian')], help_text='Book language availability', max_length=20, primary_key=True, serialize=False),
        ),
    ]
